###
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "email":"Zeeshan1234@gmail",
  "userName":"zeeshan9",
  "password":"ffff",
  "Fname":"fff",
  "Lname":"ffff",
  "phoneNumber":"ffff"
}

<> 2021-12-15T192044.500.json
###
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
"email":"jib@gmail",
"userName":"jbrn",
"password":"ffff",
"Fname":"fff",
"Lname":"ffff",
"phoneNumber":"ffff"
}
###
PUT http://localhost:8080/api/v1/user/1?userName=NEWNAMESET
Content-Type: application/json

<> 2021-12-15T192032.500.json

###
DELETE http://localhost:8080/api/v1/user/1
Content-Type: application/json

<> 2021-12-15T190933.500.json
<> 2021-12-15T185819.500.json
